name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 2024c9caf34e7c02ffc6f4c7c4558947

          # Options
          user: tpill90
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: America/New_York
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_sections: most-used
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request
          plugin_traffic: yes